// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shema/dto.proto

package classes.dto;

public final class DTOProto {
  private DTOProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DTOOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.DTO)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     * @return Whether the id field is set.
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>required string name = 2;</code>
     * @return Whether the name field is set.
     */
    boolean hasName();
    /**
     * <code>required string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>required string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required .proto.Weather weather = 3;</code>
     * @return Whether the weather field is set.
     */
    boolean hasWeather();
    /**
     * <code>required .proto.Weather weather = 3;</code>
     * @return The weather.
     */
    classes.dto.DTOProto.Weather getWeather();
    /**
     * <code>required .proto.Weather weather = 3;</code>
     */
    classes.dto.DTOProto.WeatherOrBuilder getWeatherOrBuilder();

    /**
     * <code>repeated int32 weatherStatistics = 4;</code>
     * @return A list containing the weatherStatistics.
     */
    java.util.List<java.lang.Integer> getWeatherStatisticsList();
    /**
     * <code>repeated int32 weatherStatistics = 4;</code>
     * @return The count of weatherStatistics.
     */
    int getWeatherStatisticsCount();
    /**
     * <code>repeated int32 weatherStatistics = 4;</code>
     * @param index The index of the element to return.
     * @return The weatherStatistics at the given index.
     */
    int getWeatherStatistics(int index);
  }
  /**
   * Protobuf type {@code proto.DTO}
   */
  public static final class DTO extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.DTO)
      DTOOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DTO.newBuilder() to construct.
    private DTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DTO() {
      name_ = "";
      weatherStatistics_ = emptyIntList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DTO();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DTO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
            case 26: {
              classes.dto.DTOProto.Weather.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) != 0)) {
                subBuilder = weather_.toBuilder();
              }
              weather_ = input.readMessage(classes.dto.DTOProto.Weather.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(weather_);
                weather_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 32: {
              if (!((mutable_bitField0_ & 0x00000008) != 0)) {
                weatherStatistics_ = newIntList();
                mutable_bitField0_ |= 0x00000008;
              }
              weatherStatistics_.addInt(input.readInt32());
              break;
            }
            case 34: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000008) != 0) && input.getBytesUntilLimit() > 0) {
                weatherStatistics_ = newIntList();
                mutable_bitField0_ |= 0x00000008;
              }
              while (input.getBytesUntilLimit() > 0) {
                weatherStatistics_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) != 0)) {
          weatherStatistics_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return classes.dto.DTOProto.internal_static_proto_DTO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return classes.dto.DTOProto.internal_static_proto_DTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              classes.dto.DTOProto.DTO.class, classes.dto.DTOProto.DTO.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     * @return Whether the id field is set.
     */
    @java.lang.Override
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>required string name = 2;</code>
     * @return Whether the name field is set.
     */
    @java.lang.Override
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WEATHER_FIELD_NUMBER = 3;
    private classes.dto.DTOProto.Weather weather_;
    /**
     * <code>required .proto.Weather weather = 3;</code>
     * @return Whether the weather field is set.
     */
    @java.lang.Override
    public boolean hasWeather() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required .proto.Weather weather = 3;</code>
     * @return The weather.
     */
    @java.lang.Override
    public classes.dto.DTOProto.Weather getWeather() {
      return weather_ == null ? classes.dto.DTOProto.Weather.getDefaultInstance() : weather_;
    }
    /**
     * <code>required .proto.Weather weather = 3;</code>
     */
    @java.lang.Override
    public classes.dto.DTOProto.WeatherOrBuilder getWeatherOrBuilder() {
      return weather_ == null ? classes.dto.DTOProto.Weather.getDefaultInstance() : weather_;
    }

    public static final int WEATHERSTATISTICS_FIELD_NUMBER = 4;
    private com.google.protobuf.Internal.IntList weatherStatistics_;
    /**
     * <code>repeated int32 weatherStatistics = 4;</code>
     * @return A list containing the weatherStatistics.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getWeatherStatisticsList() {
      return weatherStatistics_;
    }
    /**
     * <code>repeated int32 weatherStatistics = 4;</code>
     * @return The count of weatherStatistics.
     */
    public int getWeatherStatisticsCount() {
      return weatherStatistics_.size();
    }
    /**
     * <code>repeated int32 weatherStatistics = 4;</code>
     * @param index The index of the element to return.
     * @return The weatherStatistics at the given index.
     */
    public int getWeatherStatistics(int index) {
      return weatherStatistics_.getInt(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasWeather()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getWeather().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeMessage(3, getWeather());
      }
      for (int i = 0; i < weatherStatistics_.size(); i++) {
        output.writeInt32(4, weatherStatistics_.getInt(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getWeather());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < weatherStatistics_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(weatherStatistics_.getInt(i));
        }
        size += dataSize;
        size += 1 * getWeatherStatisticsList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof classes.dto.DTOProto.DTO)) {
        return super.equals(obj);
      }
      classes.dto.DTOProto.DTO other = (classes.dto.DTOProto.DTO) obj;

      if (hasId() != other.hasId()) return false;
      if (hasId()) {
        if (getId()
            != other.getId()) return false;
      }
      if (hasName() != other.hasName()) return false;
      if (hasName()) {
        if (!getName()
            .equals(other.getName())) return false;
      }
      if (hasWeather() != other.hasWeather()) return false;
      if (hasWeather()) {
        if (!getWeather()
            .equals(other.getWeather())) return false;
      }
      if (!getWeatherStatisticsList()
          .equals(other.getWeatherStatisticsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
      }
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasWeather()) {
        hash = (37 * hash) + WEATHER_FIELD_NUMBER;
        hash = (53 * hash) + getWeather().hashCode();
      }
      if (getWeatherStatisticsCount() > 0) {
        hash = (37 * hash) + WEATHERSTATISTICS_FIELD_NUMBER;
        hash = (53 * hash) + getWeatherStatisticsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static classes.dto.DTOProto.DTO parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static classes.dto.DTOProto.DTO parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static classes.dto.DTOProto.DTO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static classes.dto.DTOProto.DTO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static classes.dto.DTOProto.DTO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static classes.dto.DTOProto.DTO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static classes.dto.DTOProto.DTO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static classes.dto.DTOProto.DTO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static classes.dto.DTOProto.DTO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static classes.dto.DTOProto.DTO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static classes.dto.DTOProto.DTO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static classes.dto.DTOProto.DTO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(classes.dto.DTOProto.DTO prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.DTO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.DTO)
        classes.dto.DTOProto.DTOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return classes.dto.DTOProto.internal_static_proto_DTO_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return classes.dto.DTOProto.internal_static_proto_DTO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                classes.dto.DTOProto.DTO.class, classes.dto.DTOProto.DTO.Builder.class);
      }

      // Construct using classes.dto.DTOProto.DTO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getWeatherFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (weatherBuilder_ == null) {
          weather_ = null;
        } else {
          weatherBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        weatherStatistics_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return classes.dto.DTOProto.internal_static_proto_DTO_descriptor;
      }

      @java.lang.Override
      public classes.dto.DTOProto.DTO getDefaultInstanceForType() {
        return classes.dto.DTOProto.DTO.getDefaultInstance();
      }

      @java.lang.Override
      public classes.dto.DTOProto.DTO build() {
        classes.dto.DTOProto.DTO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public classes.dto.DTOProto.DTO buildPartial() {
        classes.dto.DTOProto.DTO result = new classes.dto.DTOProto.DTO(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          if (weatherBuilder_ == null) {
            result.weather_ = weather_;
          } else {
            result.weather_ = weatherBuilder_.build();
          }
          to_bitField0_ |= 0x00000004;
        }
        if (((bitField0_ & 0x00000008) != 0)) {
          weatherStatistics_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.weatherStatistics_ = weatherStatistics_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof classes.dto.DTOProto.DTO) {
          return mergeFrom((classes.dto.DTOProto.DTO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(classes.dto.DTOProto.DTO other) {
        if (other == classes.dto.DTOProto.DTO.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasWeather()) {
          mergeWeather(other.getWeather());
        }
        if (!other.weatherStatistics_.isEmpty()) {
          if (weatherStatistics_.isEmpty()) {
            weatherStatistics_ = other.weatherStatistics_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureWeatherStatisticsIsMutable();
            weatherStatistics_.addAll(other.weatherStatistics_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        if (!hasName()) {
          return false;
        }
        if (!hasWeather()) {
          return false;
        }
        if (!getWeather().isInitialized()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        classes.dto.DTOProto.DTO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (classes.dto.DTOProto.DTO) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       * @return Whether the id field is set.
       */
      @java.lang.Override
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 2;</code>
       * @return Whether the name field is set.
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      private classes.dto.DTOProto.Weather weather_;
      private com.google.protobuf.SingleFieldBuilderV3<
          classes.dto.DTOProto.Weather, classes.dto.DTOProto.Weather.Builder, classes.dto.DTOProto.WeatherOrBuilder> weatherBuilder_;
      /**
       * <code>required .proto.Weather weather = 3;</code>
       * @return Whether the weather field is set.
       */
      public boolean hasWeather() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required .proto.Weather weather = 3;</code>
       * @return The weather.
       */
      public classes.dto.DTOProto.Weather getWeather() {
        if (weatherBuilder_ == null) {
          return weather_ == null ? classes.dto.DTOProto.Weather.getDefaultInstance() : weather_;
        } else {
          return weatherBuilder_.getMessage();
        }
      }
      /**
       * <code>required .proto.Weather weather = 3;</code>
       */
      public Builder setWeather(classes.dto.DTOProto.Weather value) {
        if (weatherBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          weather_ = value;
          onChanged();
        } else {
          weatherBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .proto.Weather weather = 3;</code>
       */
      public Builder setWeather(
          classes.dto.DTOProto.Weather.Builder builderForValue) {
        if (weatherBuilder_ == null) {
          weather_ = builderForValue.build();
          onChanged();
        } else {
          weatherBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .proto.Weather weather = 3;</code>
       */
      public Builder mergeWeather(classes.dto.DTOProto.Weather value) {
        if (weatherBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
              weather_ != null &&
              weather_ != classes.dto.DTOProto.Weather.getDefaultInstance()) {
            weather_ =
              classes.dto.DTOProto.Weather.newBuilder(weather_).mergeFrom(value).buildPartial();
          } else {
            weather_ = value;
          }
          onChanged();
        } else {
          weatherBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .proto.Weather weather = 3;</code>
       */
      public Builder clearWeather() {
        if (weatherBuilder_ == null) {
          weather_ = null;
          onChanged();
        } else {
          weatherBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>required .proto.Weather weather = 3;</code>
       */
      public classes.dto.DTOProto.Weather.Builder getWeatherBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getWeatherFieldBuilder().getBuilder();
      }
      /**
       * <code>required .proto.Weather weather = 3;</code>
       */
      public classes.dto.DTOProto.WeatherOrBuilder getWeatherOrBuilder() {
        if (weatherBuilder_ != null) {
          return weatherBuilder_.getMessageOrBuilder();
        } else {
          return weather_ == null ?
              classes.dto.DTOProto.Weather.getDefaultInstance() : weather_;
        }
      }
      /**
       * <code>required .proto.Weather weather = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          classes.dto.DTOProto.Weather, classes.dto.DTOProto.Weather.Builder, classes.dto.DTOProto.WeatherOrBuilder> 
          getWeatherFieldBuilder() {
        if (weatherBuilder_ == null) {
          weatherBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              classes.dto.DTOProto.Weather, classes.dto.DTOProto.Weather.Builder, classes.dto.DTOProto.WeatherOrBuilder>(
                  getWeather(),
                  getParentForChildren(),
                  isClean());
          weather_ = null;
        }
        return weatherBuilder_;
      }

      private com.google.protobuf.Internal.IntList weatherStatistics_ = emptyIntList();
      private void ensureWeatherStatisticsIsMutable() {
        if (!((bitField0_ & 0x00000008) != 0)) {
          weatherStatistics_ = mutableCopy(weatherStatistics_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated int32 weatherStatistics = 4;</code>
       * @return A list containing the weatherStatistics.
       */
      public java.util.List<java.lang.Integer>
          getWeatherStatisticsList() {
        return ((bitField0_ & 0x00000008) != 0) ?
                 java.util.Collections.unmodifiableList(weatherStatistics_) : weatherStatistics_;
      }
      /**
       * <code>repeated int32 weatherStatistics = 4;</code>
       * @return The count of weatherStatistics.
       */
      public int getWeatherStatisticsCount() {
        return weatherStatistics_.size();
      }
      /**
       * <code>repeated int32 weatherStatistics = 4;</code>
       * @param index The index of the element to return.
       * @return The weatherStatistics at the given index.
       */
      public int getWeatherStatistics(int index) {
        return weatherStatistics_.getInt(index);
      }
      /**
       * <code>repeated int32 weatherStatistics = 4;</code>
       * @param index The index to set the value at.
       * @param value The weatherStatistics to set.
       * @return This builder for chaining.
       */
      public Builder setWeatherStatistics(
          int index, int value) {
        ensureWeatherStatisticsIsMutable();
        weatherStatistics_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 weatherStatistics = 4;</code>
       * @param value The weatherStatistics to add.
       * @return This builder for chaining.
       */
      public Builder addWeatherStatistics(int value) {
        ensureWeatherStatisticsIsMutable();
        weatherStatistics_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 weatherStatistics = 4;</code>
       * @param values The weatherStatistics to add.
       * @return This builder for chaining.
       */
      public Builder addAllWeatherStatistics(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureWeatherStatisticsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, weatherStatistics_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 weatherStatistics = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearWeatherStatistics() {
        weatherStatistics_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.DTO)
    }

    // @@protoc_insertion_point(class_scope:proto.DTO)
    private static final classes.dto.DTOProto.DTO DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new classes.dto.DTOProto.DTO();
    }

    public static classes.dto.DTOProto.DTO getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<DTO>
        PARSER = new com.google.protobuf.AbstractParser<DTO>() {
      @java.lang.Override
      public DTO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DTO(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DTO> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DTO> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public classes.dto.DTOProto.DTO getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface WeatherOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.Weather)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string data = 1;</code>
     * @return Whether the data field is set.
     */
    boolean hasData();
    /**
     * <code>required string data = 1;</code>
     * @return The data.
     */
    java.lang.String getData();
    /**
     * <code>required string data = 1;</code>
     * @return The bytes for data.
     */
    com.google.protobuf.ByteString
        getDataBytes();

    /**
     * <code>required float temperature = 2;</code>
     * @return Whether the temperature field is set.
     */
    boolean hasTemperature();
    /**
     * <code>required float temperature = 2;</code>
     * @return The temperature.
     */
    float getTemperature();
  }
  /**
   * Protobuf type {@code proto.Weather}
   */
  public static final class Weather extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.Weather)
      WeatherOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Weather.newBuilder() to construct.
    private Weather(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Weather() {
      data_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Weather();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Weather(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              data_ = bs;
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              temperature_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return classes.dto.DTOProto.internal_static_proto_Weather_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return classes.dto.DTOProto.internal_static_proto_Weather_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              classes.dto.DTOProto.Weather.class, classes.dto.DTOProto.Weather.Builder.class);
    }

    private int bitField0_;
    public static final int DATA_FIELD_NUMBER = 1;
    private volatile java.lang.Object data_;
    /**
     * <code>required string data = 1;</code>
     * @return Whether the data field is set.
     */
    @java.lang.Override
    public boolean hasData() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string data = 1;</code>
     * @return The data.
     */
    @java.lang.Override
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          data_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string data = 1;</code>
     * @return The bytes for data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TEMPERATURE_FIELD_NUMBER = 2;
    private float temperature_;
    /**
     * <code>required float temperature = 2;</code>
     * @return Whether the temperature field is set.
     */
    @java.lang.Override
    public boolean hasTemperature() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required float temperature = 2;</code>
     * @return The temperature.
     */
    @java.lang.Override
    public float getTemperature() {
      return temperature_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTemperature()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, data_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeFloat(2, temperature_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, data_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, temperature_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof classes.dto.DTOProto.Weather)) {
        return super.equals(obj);
      }
      classes.dto.DTOProto.Weather other = (classes.dto.DTOProto.Weather) obj;

      if (hasData() != other.hasData()) return false;
      if (hasData()) {
        if (!getData()
            .equals(other.getData())) return false;
      }
      if (hasTemperature() != other.hasTemperature()) return false;
      if (hasTemperature()) {
        if (java.lang.Float.floatToIntBits(getTemperature())
            != java.lang.Float.floatToIntBits(
                other.getTemperature())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasData()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
      }
      if (hasTemperature()) {
        hash = (37 * hash) + TEMPERATURE_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getTemperature());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static classes.dto.DTOProto.Weather parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static classes.dto.DTOProto.Weather parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static classes.dto.DTOProto.Weather parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static classes.dto.DTOProto.Weather parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static classes.dto.DTOProto.Weather parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static classes.dto.DTOProto.Weather parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static classes.dto.DTOProto.Weather parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static classes.dto.DTOProto.Weather parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static classes.dto.DTOProto.Weather parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static classes.dto.DTOProto.Weather parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static classes.dto.DTOProto.Weather parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static classes.dto.DTOProto.Weather parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(classes.dto.DTOProto.Weather prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.Weather}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.Weather)
        classes.dto.DTOProto.WeatherOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return classes.dto.DTOProto.internal_static_proto_Weather_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return classes.dto.DTOProto.internal_static_proto_Weather_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                classes.dto.DTOProto.Weather.class, classes.dto.DTOProto.Weather.Builder.class);
      }

      // Construct using classes.dto.DTOProto.Weather.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        data_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        temperature_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return classes.dto.DTOProto.internal_static_proto_Weather_descriptor;
      }

      @java.lang.Override
      public classes.dto.DTOProto.Weather getDefaultInstanceForType() {
        return classes.dto.DTOProto.Weather.getDefaultInstance();
      }

      @java.lang.Override
      public classes.dto.DTOProto.Weather build() {
        classes.dto.DTOProto.Weather result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public classes.dto.DTOProto.Weather buildPartial() {
        classes.dto.DTOProto.Weather result = new classes.dto.DTOProto.Weather(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.data_ = data_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.temperature_ = temperature_;
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof classes.dto.DTOProto.Weather) {
          return mergeFrom((classes.dto.DTOProto.Weather)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(classes.dto.DTOProto.Weather other) {
        if (other == classes.dto.DTOProto.Weather.getDefaultInstance()) return this;
        if (other.hasData()) {
          bitField0_ |= 0x00000001;
          data_ = other.data_;
          onChanged();
        }
        if (other.hasTemperature()) {
          setTemperature(other.getTemperature());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasData()) {
          return false;
        }
        if (!hasTemperature()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        classes.dto.DTOProto.Weather parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (classes.dto.DTOProto.Weather) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object data_ = "";
      /**
       * <code>required string data = 1;</code>
       * @return Whether the data field is set.
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string data = 1;</code>
       * @return The data.
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            data_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string data = 1;</code>
       * @return The bytes for data.
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string data = 1;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string data = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <code>required string data = 1;</code>
       * @param value The bytes for data to set.
       * @return This builder for chaining.
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        data_ = value;
        onChanged();
        return this;
      }

      private float temperature_ ;
      /**
       * <code>required float temperature = 2;</code>
       * @return Whether the temperature field is set.
       */
      @java.lang.Override
      public boolean hasTemperature() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required float temperature = 2;</code>
       * @return The temperature.
       */
      @java.lang.Override
      public float getTemperature() {
        return temperature_;
      }
      /**
       * <code>required float temperature = 2;</code>
       * @param value The temperature to set.
       * @return This builder for chaining.
       */
      public Builder setTemperature(float value) {
        bitField0_ |= 0x00000002;
        temperature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float temperature = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTemperature() {
        bitField0_ = (bitField0_ & ~0x00000002);
        temperature_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.Weather)
    }

    // @@protoc_insertion_point(class_scope:proto.Weather)
    private static final classes.dto.DTOProto.Weather DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new classes.dto.DTOProto.Weather();
    }

    public static classes.dto.DTOProto.Weather getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Weather>
        PARSER = new com.google.protobuf.AbstractParser<Weather>() {
      @java.lang.Override
      public Weather parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Weather(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Weather> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Weather> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public classes.dto.DTOProto.Weather getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_DTO_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_DTO_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Weather_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Weather_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017shema/dto.proto\022\005proto\"[\n\003DTO\022\n\n\002id\030\001 " +
      "\002(\005\022\014\n\004name\030\002 \002(\t\022\037\n\007weather\030\003 \002(\0132\016.pro" +
      "to.Weather\022\031\n\021weatherStatistics\030\004 \003(\005\",\n" +
      "\007Weather\022\014\n\004data\030\001 \002(\t\022\023\n\013temperature\030\002 " +
      "\002(\002B\027\n\013classes.dtoB\010DTOProto"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_proto_DTO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_DTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_DTO_descriptor,
        new java.lang.String[] { "Id", "Name", "Weather", "WeatherStatistics", });
    internal_static_proto_Weather_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_Weather_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Weather_descriptor,
        new java.lang.String[] { "Data", "Temperature", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
